### ISSUE TITLE
v1.10.0.103 - Files' modes not appropriate

### ISSUE THREAD

**Issue by minami-o** [RainLoop/rainloop-webmail#1033]
Hi there,
I just downloaded the latest version of the Community edition (1.10.0.103), and unzipped it as usual in my rainloop reference folder.
When trying to access the url, I faced a 105 error "Missing version directory".
I checked for the files and folders, everything was in place, but I noticed they were almost all in change mode but with no execution rights (like 666).
The issue (to not be able to access the url) is caused by the missing execution bit on some folders, but the change mode is also a mistake, as it seems rather insecure to let everyone change the files of such an important app.
These modes were obviously correct in previous versions of the app, so I guess it's an accident.
For testing purposes, I removed the change mode and set the execution mode for the whole rainloop subfolder and its contents (ie. the v folder and versions folders it contains), and it solved the issue.
Could you please have a look?

Edit: it looks like only *subfolders* are missing the +x mode, so a command like "find rainloop/ -type d -exec chmod 755 {} \;" is enough, no need to make all files executable as well.

**Comment by RainLoop** [comment]
Some write permissions are required for "One click update" functionality in Standard edition:

![image](https://cloud.githubusercontent.com/assets/5530092/15191106/ca611234-17bb-11e6-8599-bce486cb2640.png)

But you right, in the Community edition you may to remove the change mode from files, because you update RainLoop manually.

There is some [documentation](http://www.rainloop.net/docs/permissions/), but I have no time to write more information about Community edition and additional security configuration.

**Comment by minami-o** [comment]
Wow, totally forgot to check this piece of documentation, sorry for this!
I had a look and applied the recommendations when I installed a while ago, but then, as appropriate rights were always in place in the zips, I forgot about them.
The available documentation is definitely enough, I think, but you can't force idiots like me to rtfm :)
Thanks for your quick reply!
