### ISSUE TITLE
strange quoting behaviour

### ISSUE THREAD

**Issue by derStephan** [RainLoop/rainloop-webmail#1225]
When I reply to an eMail, I often split the original message in parts and answer directly to them as it is described here:

https://www.netmeister.org/news/learn2quote2.html#ss2.3

![write_mail_with_inline_quotes](https://cloud.githubusercontent.com/assets/7764931/19547706/300e1462-969a-11e6-8421-a21e21541a62.png)

But when reading such a message in rainloop, the inline quotes are collapsed.

![read_mail_with_inline_quotes](https://cloud.githubusercontent.com/assets/7764931/19547721/4702cad2-969a-11e6-8e5d-85c890701fc2.png)

I think, collapsing quotes at the end of the message is very useful. But collapsing inline quotes does not make much sense because it leads to the complete opposite of what inline quotes are supposed to be. 

May I suggest to change this behaviour to not collapsing inline quotes unless they are longer than a couple of lines?

**RainLoop version, browser, OS:**

rainloop: 1.10.4.183
firefox 49.0.1

**Comment by derStephan** [comment]
great!! Thanks. :smile:

**Comment by megadr01d** [comment]
> May I suggest to change this behaviour to not collapsing inline quotes unless they are longer than a couple of lines?

@RainLoop I'm sorry to bring back this issue but I think this got more confusing. Because the blockquoting buttons [...] don't have a expand/collapse state, and taking example in the screenshot below, do I have a collapsed blockquote before **2 months** or is the blockquote already expanded?

In examples like this, like news feeds, it's common to have lots of quoting so it gets even more confusing since some are collapsed while others are expanded by default (based on number of characters/lines).

If there's a chance this can be reviewed, consider makeing all blockquotes collapsed or expanded by default. This way I know that by pressing <kbd>B</kbd> I'll be expanding/collapsing **all** blockquotes.

Maybe even @derStephan original issue was created without the knowledge of that global shortcut key.

![blockquote](https://user-images.githubusercontent.com/9649385/29922747-d15b8578-8e4e-11e7-84cc-960523f8df39.png)
