### ISSUE TITLE
No version 4.27 in nextcloud store

### ISSUE THREAD

**Issue by muppeth** [RainLoop/rainloop-webmail#1297]
I noticed that nextcloud store hasn't been updated to latest 4.27 version. I tried using the version from apps.owncloud.com but that doesn't seem to work and I'm notified to update to previous version 4.26

**Comment by pierre-alain-b** [comment]
Yes, this is true. The version currently present in the Nextcloud store is here:
https://github.com/pierre-alain-b/rainloop-nextcloud
This is basically version 4.26.
I should take some time to do the update.

If someone of the Rainloop team could approach me, we could see how we could best mutualize the effort for the generation of the owncloud & nextcloud apps.

**Comment by pierre-alain-b** [comment]
Same question expressed here: https://github.com/pierre-alain-b/rainloop-nextcloud/issues/5

**Comment by DJCrashdummy** [comment]
this leads to the paradox situation that until nexcloud 10 the latest version of rainloop (1.10.5.192) is installed (because the owncloud-apps are used) and starting with nextcloud 11 you get version 1.10.4.183 of rainloop.

additional i have to say i'm not really sure about the rainloop-development right now...
at least the issues seems to be completely unmaintained, no reactions/comments from @RainLoop and the "trigger-issue" https://github.com/RainLoop/rainloop-webmail/issues/479 for new releases was closed on the day of the last release (06.11.2016) without even mentioning it!?! :-(

**Comment by pierre-alain-b** [comment]
I think #479 is closed only to prevent comments - so that only the Rainloop team can activate the trigger for all those who subscribed to it.
As soon as I have some free time, I will try to to use the last release in the Nextcloud app.

**Comment by pierre-alain-b** [comment]
That being said, 1.10.5.192 was not mentioned on the trigger issue.

**Comment by DJCrashdummy** [comment]
> I think #479 is closed only to prevent comments

well... as you can see https://github.com/RainLoop/rainloop-webmail/issues/479#event-646621524, it was locked and limited more than a half year before.


- there is no roadmap or not even milestones published, also a question about it https://github.com/RainLoop/rainloop-webmail/issues/702 was ignored
- exact like a question for documentation https://github.com/RainLoop/rainloop-webmail/issues/898

 
_all this evidences gives me a disquieting feeling about further development, although code was contributed after the last release..._

i hope to see some actions or at least a statement of @RainLoop (on github or their website) because i'm afraid this is also bad for their business model (https://www.rainloop.net/purchase/)...
because unfortunately i won't purchase a software in such a uncertain state and with obviously zero support. :-(

**Comment by pierre-alain-b** [comment]
Fixed, 4.27.0 for nextcloud is now available in the nextcloud apps store!

**Comment by pierre-alain-b** [comment]
I suggest to fix this issue.

**Comment by DJCrashdummy** [comment]
maybe @muppeth or @RainLoop can close this issue?
