### ISSUE TITLE
What does the SPAM button do in Rainloop?

### ISSUE THREAD

**Issue by bms8197** [RainLoop/rainloop-webmail#1330]
Could someone please explain me what exactly does the Spam button in Rainloop other that moving that email to the Spam folder?

Is there anyway to assign a specific action on that spam button? Like for example when I have a spam email in my box, I usually manually do a sa-learn --spam email-id (so spamassassin will learn that email as spam and block it).

**Comment by ervee** [comment]
It just moves the mail to your defined Spam system folder.
When you want to learn it as Spam with sa-learn you have (IMHO) 2 options:
1) 

1. Make a script to train sa-learn with the users spam box. Something like this: http://xyzzyxyzzy.net/2012/09/15/spamassassin-learning-from-inbox-and-junk-folders/
2. Use the Dovecot spugin dovecot-antispam to feed spam to sa-learn when a user moves mail to the spam box.

You won't be able to have RainLoop itself trigger a sa-learn because RainLoop could be separated from your mailserver. How will it trigger sa-learn? There is no interface other than  dovecot-antispam that I know of.

**Comment by bms8197** [comment]
Ok, I'll try that. I didn't consider the option that rainloop cand be on another server since in my scenario they are on the same server. Good observation though. Thanks!

**Comment by M66B** [comment]
The Dovecot antispam plugin is deprecated, see here for the alternative:

https://wiki2.dovecot.org/HowTo/AntispamWithSieve

**Comment by ervee** [comment]
Interesting. Going to look into that. Thanks for pointing it out.
