### ISSUE TITLE
[feature request] option to put in html source code

### ISSUE THREAD

**Issue by violoncelloch** [RainLoop/rainloop-webmail#1449]
**RainLoop version, browser, OS:** RainLoop in Nextcloud 5.0.0, Firefox, Win10

**Expected behavior and actual behavior:** option to past html source code (e.g. for the signature)

**Steps to reproduce the problem:** try to put in html code -> not rendered

**Comment by grupografcol** [comment]
Hi, i`ve the same problem, any solution?

**Comment by jones4410** [comment]
I found a way to make it work, but I don't remember exactly what it was... I think the problem is there is an additional hidden button to input html. The first one is to switch between html and txt and the "html source code" button is only showed after enabling it in a config file.
maybe you can find the config file by searching the web?

**Comment by akmet** [comment]
Found the following 2 settings in application.ini:
```
allow_html_editor_source_button = Off
allow_html_editor_biti_buttons = Off
```
Try setting them to On :-)
