### ISSUE TITLE
no issue, question about spam button

### ISSUE THREAD

**Issue by fsantiago07044** [RainLoop/rainloop-webmail#1515]
question; in the current rainloop version, what does the spam button do? does it in anyway integrate with sa or the like? or does it simply move the mail into a spam/junk folder with no further action? does it build it's own internal spam filtering database? just curious. thanks.

**Comment by ervee** [comment]
It only moves to the folder you set as spam folder in system settings. If you want to integrate with SA etc. you'll have to run sa-learn every once in a while or have your IMAP server trigger something when you move mail to the spam folder. There has been discussion about this before, I'm sure you can find the issue when you search a bit. 

I (note I'm not a RainLoop developer) think it's not up to RainLoop to trigger some action. Especially because RainLoop and mailserver (and anti spam solution) do not have to run on the same server.

**Comment by fsantiago07044** [comment]
September 27, 2017 12:28 PM, "Ralf" <notifications@github.com> wrote:

> It only moves to the folder you set as spam folder in system settings. If you want to integrate
> with SA etc. you'll have to run sa-learn every once in a while or have your IMAP server trigger
> something when you move mail to the spam folder. There has been discussion about this before, I'm
> sure you can find the issue when you search a bit.
> 
> I (note I'm not a RainLoop developer) think it's not up to RainLoop to trigger some action.
> Especially because RainLoop and mailserver (and anti spam solution) do not have to run on the same
> server.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

ok thanks. i was just curious. i'm not asking about any addt'l functionality. Roundcube which i've also used does have a plugin that offers direct sa integration for spam/ham learning on the fly. 

--

Thanks,

Fabian S.

OpenPGP: 3C3FA072ACCB7AC5DB0F723455502B0EEB9070FC

**Comment by megadr01d** [comment]
https://github.com/RainLoop/rainloop-webmail/issues?utf8=✓&q=spam%20button
