### ISSUE TITLE
What does add account mean?

### ISSUE THREAD

**Issue by elgs** [RainLoop/rainloop-webmail#1875]
I saw an option as add account from the user menu? I don’t understand what it means? Rainloop doesn’t know the credentials of my user db, how does it add account?

**Comment by ivnmad** [comment]
Rainloop must have your DB credentials (at least for the Rainloop DB) otherwise it cannot work.

You can setup Rainloop to manage multiple domains.
Add account allows the user to add additional email addresses that are either part of the same domain they are currently using, or part of the allowed domains, as long as the user has the credentials to log in into those email addresses.

E.g. my email address is john@rainloop.example
I could add peter@rainloop.example if I also owed that email address and I have the credentials to log in. I could also john@example.rainloop if that domain was also setup and allowed by the administrator.

**Comment by ivnmad** [comment]
BTW, the database is also used to store contacts.

**Comment by elgs** [comment]
@ivnmad thank you so much for clearly explaining it to me. I found all the magic here: `rainloop/data/_data_/_default_/storage/cfg`.
