### ISSUE TITLE
[MiTM] Certificates are not validated?

### ISSUE THREAD

**Issue by kbabioch** [RainLoop/rainloop-webmail#332]
Hi,

I'm using a self-signed certificate for my IMAP server. I could add the connection details to the list of valid domains and it just worked (TM) without asking me to add an exception and/or notifying me at all. I have not investigated this any further, but I would absolutely expect to get a warning and to have to add the root CA certificate.

**Comment by lakano** [comment]
Hello,

May be this could help, there is some informations about significant changes since PHP 5.6 on the TLS streams: 
http://php.net/manual/en/migration56.incompatible.php

Currently, I'm under PHP 5.5.9 ( Ubuntu Server, packagers explain they will not upgrade php6 because of backward incompatibilities )

I'm trying to use RainLoop inside OwnCloud 8.1, I can't connect to my own mail server with a self-signed cert.

May be I need to upgrade to PHP 5.6, but I'm afraid of the backward compatibility with OwnCloud and all 3rd party applications installed.

Regards,

**Comment by RainLoop** [comment]
Well, I have added some additional configurations in application.ini that can help.

```ini
[ssl]
; Location of Certificate Authority file on local filesystem (/etc/ssl/certs/ca-certificates.crt)
cafile = "" 
; capath must be a correctly hashed certificate directory. (/etc/ssl/certs/)
capath = ""
```

**Comment by lakano** [comment]
:+1: 
BTW, I'm testing with PHP 5.6 (from an external source)... same problem with my self-signed certs.
But I have updated by certs with one from StartSSL (free), now it's works.
