### ISSUE TITLE
Sieve rules

### ISSUE THREAD

**Issue by offspringus** [RainLoop/rainloop-webmail#428]
Hello,
I want to ask. Before I started using Rainloop, I used roundcube and created some sieve filters to manage my mails in some folders. Now, I go to Rainloop settings and could add sieve rules but I don't see my old filters that is working good for now. Is it normal?

Also, thanks for good product.

**Comment by RainLoop** [comment]
Yes, it is normal, you need to re-create all your filters in the RainLoop.

**Comment by offspringus** [comment]
Ok, thanks for answer.

**Comment by dharmann** [comment]
I wish to reopen this issue, because Sieve is a standard protocol and I wish to use it across multiple devices.
For instance:
I've created a tons of filters through RainLoop.
I have my MUA (I'm a KMail user too) and I need to modify my sieve script from here.
When I'll back to RainLoop, I wish to reopen my updated/new filters and manage these.
Sieve itself permit it, but not RainLoop, because is unable to read standard filters.

In my opinion, this is not a feature, this is a bug.
