### ISSUE TITLE
Website: Missing information about the company

### ISSUE THREAD

**Issue by hachre** [RainLoop/rainloop-webmail#450]
I'm just posting this to let you know that not posting any info about the company or the people behind the project on the website is going to reduce trustworthiness for business customers and thus result in fewer sales. 

Any info on these topics is better than no info at all.

Info that is missing:
- Company Name (or is RainLoop the company name as well as the product name?)
- Company Location
- Project Leader (Name, what else has he done before)
- Team Size (don't be shy to say that you're writing this alone or with a buddy, if you are)
- who are the guys on the team, are they known for anything else?

Without these things posted the site looks good on first glance, but when you ask business customers to pay they will quickly start looking around for the info about "who am I paying here" and then notice that this info has been omitted, which makes the whole thing look somewhat fishy.

Please consider adding those things.

**Comment by ervee** [comment]
+1
Even though I'm not a business user. I'm working in ICT so I just might be one day. Or possibly recommend RainLoop.

**Comment by mailbee** [comment]
Here's RainLoop story, for those who's interested.

For many years, Timur Usenko has been the developer in AfterLogic Corp involved in making [AfterLogic WebMail Pro](http://www.afterlogic.com/webmail-client) and [AfterLogic WebMail Lite](http://afterlogic.org/webmail-lite) products.

At some moment Timur started experimenting with a new IMAP engine library which encapsulated all the experience our team gained for years of webmail and mail components making. Initially it was more like a hobby for Timur but over the time the library was considered quite good and included in the next version of our webmail (and the current version uses this library, MailSo). Before the release of AfterLogic WebMail version based on MailSo, Timur also made a simple webmail app which acted as a testing platform for this library (at least as we thought).

What we couldn't expect is that Timur planned to further develop this app into a product which'd compete with the company where he's working, moreover, sell it. For a while we've tried to convince Timur to stop making competition to the company which's paying him salary but it never worked out and finally we had to fire him.

As RainLoop contains intellectual property we consider to be belonging to AfterLogic (with Timur indeed being an author but not real copyright holder), we would do our best to sue any legal entity behind RainLoop whenever it appears in USA, EU or any other countries respecting law. Currently, as Timur's country of residence is Russia (where AfterLogic's development department is located), it's possible for him to continue this activity. Under current circumstances, I guess Timur doesn't have much interest in disclosing legal details behind his business due to its questionable nature.

P.S. If you do some googling on afterlogic rainloop, I think you'll easily find posts which show how surprisingly closely RainLoop's design idea resembles AfterLogic. Even on this github tracker:
[https://github.com/RainLoop/rainloop-webmail/issues/232](https://github.com/RainLoop/rainloop-webmail/issues/232)

**Comment by mike-anthony** [comment]
Hmmm, this is interesting.

Quite questionable regarding the design. To me, they do not look the same. Mail clients all follow a similar layout. The only real match I can find is regarding the overlapping panels with rounded corners. Other than that, RainLoop's design (look and feel, specifically) seems original.

Look, the way I see this: RainLoop is a great product and project. Many companies (and projects) have interesting, and perhaps questionable, back-stories.

That aside, I do think that there should be a tad more info on the site, per the OPs recommendation.

**Comment by hachre** [comment]
The do look quite similar to me, but the way I understand @mailbee's post, the actual legal discussion centers around him developing a competing webmail product, which he then put up for sale, while being employed by Afterlogic.

This is certainly morally problematic, but I don't think this alone will hold up in court. Even though he had direct access to knowledge there, which he used to write his own product, the AfterLogic Webmail-Lite is open source and that would allow anyone even outside the company to simply read the code, be inspired by it, and write their own backend engine and eventually web mailer around it.

But then again I'm no lawyer and it is up to courts to decide this, if it were to get to that.

Anyway, it is an insightful story and certainly explains why there is so little legally useable info on RainLoop's website - thanks @mailbee !

**Comment by RainLoop** [comment]
> As RainLoop contains intellectual property we consider to be belonging to AfterLogic
> (with Timur indeed being an author but not real copyright holder).

Is the MailSo library a intellectual property of AfterLogic? AfterLogic never ask me to do something like that. 

MailSo library (MIT license) was developed by me in personal time, and was used in many of the project (RainLoop, AfterLogic Webmail and others where I had to work with mails).

> which encapsulated all the experience our team gained for years
it's a very strong exaggeration.

**Comment by RainLoop** [comment]
> Anyway, it is an insightful story and certainly explains 
> why there is so little legally useable info on RainLoop's website.

I'm just not a great expert in all of this.

**Comment by hachre** [comment]
@RainLoop You can get started by adding a little info about yourself (maybe city and country, not an exact address), team size (just you?), when the project got started, history of the project, and this whole backstory to the site. This way you have an opportunity to publish your side of the story. If you have no company, then this would certainly suffice and be a lot better than the amount of info that is on the site right now.

**Comment by arturbonnett** [comment]
In fact I've had this curiosity before, and I liked to know better about Rainloop's story. It may be interesting to put some information on the site.
I see nothing wrong with that. Timur merits! You realy do a great job here.

**Comment by mailbee** [comment]
@hachre 
> the AfterLogic Webmail-Lite is open source and that would allow anyone even outside the company to simply read the code, be inspired by it, and write their own backend engine and eventually web mailer around it.

The important nuance is that you can't change the license then. Legally speaking, any project sharing  any portion of codebase with WebMail Lite would need to keep its AGPL license. Rainloop, however, is dual licensed with CC and commercial license. If any company or person develops a webmail product which involves our code and changes the license without our permission, it will still be illegal regardless of any other facts and matters.

**Comment by hachre** [comment]
@mailbee Yes, but the license only applies to actually copying the code and then altering it.

From what I understood he wrote a new thing (both backend and eventually frontend) from the ground up and only used the existing knowledge he had of the current AGPL code as his inspiration for it. The grade of "inspiration" is the thing that a court will have to ascertain in this case. 

I totally understand where you're coming from, but at least in my unprofessional legal opinion, this isn't a clear cut case.

**Comment by RainLoop** [comment]
MailSo library has never been AGPL.
You have changed license to AGPL (without my approval) after I left. Which is a violation, as soon as only I can to change the license of this library.

**Comment by mailbee** [comment]
@hachre Still there is plenty of code which is identical in both products so it's not just "ideas". All of that code was of Timur's authorship which he thinks is equal to copyright but I don't want to go into endless flames war here and post code blocks or all that screenshots with timestamps of Rainloop commits made in Timur's working time in AfterLogic office and similar materials which are better to be used in the court.

I just wanted to share my vision of things if anybody interested, and won't be spending more time on this topic - have real work to do. It's up to people to decide. Thanks for listening.

**Comment by hachre** [comment]
@mailbee Thanks for posting! No need for flame wars :) We know both sides of the story now, which is all we could ask for.

**Comment by ervee** [comment]
Google's your friend, I just stumbled upon this nice interview: https://entwickler.de/webandphp/open-source-spotlight-rainloop-125690.html

**Comment by afterlogic** [comment]
Now I see that even web site content of rainloop.net on some pages is basically copy-paste of afterlogic.com
![scrshot](https://cloud.githubusercontent.com/assets/4507359/7497587/0940c6e6-f424-11e4-943c-d59dec1e34d4.png)
Bravo, Timur, nice work. Keep stealing from us! You're the best in this.

**Comment by DamienR** [comment]
> What we couldn't expect is that Timur planned to further develop this app into a product which'd 
> compete with the company where he's working, moreover, sell it. For a while we've tried to convince 
> Timur to stop making competition to the company which's paying him salary but it never worked
> out  and finally we had to fire him.

This is pretty much how the developers of Vbulletin left and created Xenforo, Vbulletin sued in USA and UK and lost both cases. You'd lose as well.

**Comment by hardhub** [comment]
@mailbee 

Do you have any proofs?  
Contract with developer?  
Tasks (regarding mail) in task management software?  
It is possible that he did it as hobby and shared with you.  
And you used it as part of your product being sure it is yours.  
I personally think that nobody (company or author) say us all truth.

**Comment by mailbee** [comment]
It's expected for a company employee not to perform activities which can do harm for the company he's working in. In our opinion, developing a competitive product is an example of harmful activity.

Moreover, Timur often worked on this product in his work time sitting in our office. So it can't be considered hobby work even from that point of view (despite the fact he worked on a competitive product, not just some software unrelated to our business). If you need proofs, you can contact us directly.

**Comment by hardhub** [comment]
@mailbee 

OK, but if you have proofs why you are not in court?  

Because we have an alternative opinion:

> Is the MailSo library a intellectual property of AfterLogic? AfterLogic never ask me to do something like that.
>MailSo library (MIT license) was developed by me in personal time, and was used in many of the project > (RainLoop, AfterLogic Webmail and others where I had to work with mails).

It is words vs words. At least it looks exactly so without proofs available to potentials users.

My point of view: if you want to warn users or stop this project you need more than just words.  
Please understand correctly... I can go right now to any repo and say it is the property of my company (with the same result of course).
