### ISSUE TITLE
Beta 1.8.2 (beta 2)

### ISSUE THREAD

**Issue by RainLoop** [RainLoop/rainloop-webmail#523]
Package:
http://repository.rainloop.net/v2/webmail/1.8.2/rainloop-1.8.2.288-2216a7aa6b42e609ef38bdea7af53966.zip

![th01](https://cloud.githubusercontent.com/assets/5530092/6652089/b737afe8-ca72-11e4-9a93-5b878ae66e97.png)

What do you think?

**Comment by ervee** [comment]
Hi, sorry I didn't test this and the previous Beta earlier. I was a bit short on time :)

Here are my findings:
* I notice the indicator of how much messages there are in a thread has changed from a box with a number in it in front of the sender name, to a number between ( ) after the sender name. I don't think both of these are an improvement.
* I notice you can't expand an email thread in the main message list anymore.
* When using the < and > buttons to go through the messages is a thread all goes well, but if I press the button in between and select a message in the list it often (most of the time) sends me back to the message list... Sometimes it opens the message as it should. And sometimes the screen shows the message list briefly and then shows the message.
* And somehow when the message subject is long, it overwrites the time/date indicator. ![capture](https://cloud.githubusercontent.com/assets/4435930/6655756/2952dc0e-cb0b-11e4-8eba-079ef542036a.JPG) It's weird that's not the case in your screenshot where the time/date indicator is in line with the sender instead of the subject.

Ralf.

**Comment by RainLoop** [comment]
@ervee 
Thanks!
> 1)

![image](https://cloud.githubusercontent.com/assets/5530092/6658225/85efba28-cb73-11e4-8954-0f1a6d189b2d.png)

What do you think?

> I notice you can't expand an email thread in the main message list anymore.

Yes, now it works that way.

New version with fixes:
http://repository.rainloop.net/v2/webmail/1.8.2/rainloop-1.8.2.288-2216a7aa6b42e609ef38bdea7af53966.zip

**Comment by arturbonnett** [comment]
Pretty cool this last one!!! :smiley:
Working fine here :+1:

**Comment by ervee** [comment]
Message indicator looks good to me. The problems I found are not there anymore so that looks solved :)

**Comment by megadr01d** [comment]
I like it too. When using threads I think this is a clutter-free approach. Just a question, are we also getting keyboard shortcuts to switch to previous/next thread?

**Comment by RainLoop** [comment]
> Just a question, are we also getting keyboard shortcuts to switch to previous/next thread?

Yes, `Ctrl + -->` and `Ctrl + <--`

**Comment by megadr01d** [comment]
:+1:

**Comment by RainLoop** [comment]
Release Candidate:
http://repository.rainloop.net/v2/webmail/1.8.2/rainloop-1.8.2.290-95bb2c2f2250f7c7d56bd63a4010b1c5.zip

**Comment by ervee** [comment]
Still looking good. But can we get the ```Ctrl + -->``` and ```Ctrl + <--``` for regular messages too?

**Comment by RainLoop** [comment]
Do you use "no preview pane" layout?
`Ctrl + up` and `Ctrl + down`

**Comment by ervee** [comment]
SWEEEEEEEEET!

Yes I use no preview pane. :-D

**Comment by arturbonnett** [comment]
Pretty good!! =)

The keyboard shortcuts working well!
I can use arrows on Thread List box, good! But to get the box is required to click on Thread List button.
Do you think would be interesting a shortcut to open the Thread List too?
I don't mind having to click, but soon it can be requested here

**Comment by RainLoop** [comment]
> Do you think would be interesting a shortcut to open the Thread List too?

`T` button.

**Comment by megadr01d** [comment]
I just noticed that you can't delete a single message from a thread (the toolbar buttons get grayed-out except on the first message) so you have to delete the whole thread. I'm almost sure you could do it when you could expand threads in the message list.

**Comment by RainLoop** [comment]
> I just noticed that you can't delete a single message from a thread

You can do it using "more" drop down of selected message.

![image](https://cloud.githubusercontent.com/assets/5530092/7140717/88c41ba8-e2d5-11e4-841c-e7fe5040f7bf.png)

**Comment by megadr01d** [comment]
Of course, the only place I forgot too look. Thanks and sorry for the noise.
