### ISSUE TITLE
GPG support

### ISSUE THREAD

**Issue by rsertelon** [RainLoop/rainloop-webmail#53]
Hi,

I just stumble upon your project. It looks really nice, by far one of the best interfaces in open source webmails.

Do you plan to add support for GPG encryption? Roundcube has a GPG plugin that works quite well. MailPile is planning to integrate GPG from the ground up (in its architecture).

In these times where our privacy is endangered by mass surveillance, this would be very nice :)

Just my 2 cents!

Regards,

**Comment by kesavanm** [comment]
Thanks for the awesome product. 
Can we store the OpenPGP `keys` in the server side instead of browser local storage ?  In that case , I can use the keys regardless of browser I use as well as on-the-go mobile device , wherever I'm .

Since the key stored at server (web host) , I feel that's safe and secure , access is limited. I thought of sessions Vs Cookies. Correct me if I'm wrong.Browser cache can be accessed by one who , right?

**Comment by rsertelon** [comment]
@kesavanm It's common good practice not to give your private key to anyone, even what would be a "secure" web host. This key is the only one that proves that's really you. So you should try hard to limit its exposure.

This is the general problem encountered with PGP, keys storage is the least convenient thing in PGP (IMHO).

**Comment by zeigerpuppy** [comment]
storing public keys in the contacts would be a more logical place for these.  It's also quite safe to store public keys server-side.
