### ISSUE TITLE
Contacts not available with RainLoop owncloud-app from direct URL

### ISSUE THREAD

**Issue by jelle-e** [RainLoop/rainloop-webmail#553]
While it is indeed possible to open the RainLoop-app for owncloud directly (from URL: https://myowncloud.domain.com/index.php/apps/rainloop/app/), RainLoop can't access the contacts of owncloud. Is this issue inevitable or can it be solved?

Of course the contacts addressbook does work when first logging into owncloud, then on the email app for RainLoop.

**Comment by deMattin** [comment]
To get contacts from owncloud, it is neccessary to be logged in in owncloud.
If you log out in owncloud and start rainloop with **your** direct link you don't use owncloud authentifiation:

Use https://myowncloud.domain.com/index.php/apps/rainloop/ instead and you get the login screen of owncloud. Then you log in with your owncloud credentials and are directly in rainloop mail.
If you use permanent authentification (remember login) via cookies in owncloud, you don't need to give credentials at all.

I use it like this since I integrated rainloop in owncloud and have this link as favorite to check mails fast without first starting owncloud and then switching to rainloop.

**Comment by jelle-e** [comment]
Right, I understand, thanks.
Then it's not possible to serve only mail to some users without ownCloud while having RainLoop integrated in ownCloud. Seems logical when we speak about it, but I didn't realize this when installing. I guess I have to give everyone an ownCloud account if they want to be able to use/store their contacts.

**Comment by jelle-e** [comment]
Just to add a note: ...then the original implementation of RainLoop (with syncing the addressbooks while staying seperate) wasn't that bad at all. People could use the addressbook without ownCloud account but also with one...

**Comment by deMattin** [comment]
Rainloop has it's own standalone contacts database but it is deactivated, if you integrate rainloop via owncloud app.
This is a good decision, if you have a onwcloud account but makes it impossible to use it like you want.

Maybe there is a solution for your task:
If rainloop developer sees a way to activate rainloop sql database if you log in directly (via your link in first post) without using owncloud credentials and so **only** users without owncloud account use the rainloop adress database.
But it could be a problem, if someone with owncloud account also logs in directly.
This shouldn't be done because this could lead in two contact lists depending on the way you logged in.

The contacts sync wasn't very reliable in my opinion. It worked but integrating owncloud contacts is really the best way. Only adding contacts from rainloop in owncloud contacts is a still missing request.

Let's see what "Mister rainloop" says to it ... :wink:

**Comment by jelle-e** [comment]
Yes, that's well put. I agree. Because of the problem you're describing I don't think activating the RainLoop sql DB should be done while integrated in ownCloud. If I really want a seperate mail-only solution, I will install a seperate instance of RainLoop. (altough I'll have to buy it twice then...)

Indeed storing addresses from rainloop to ownCloud would be great to have!

**Comment by deMattin** [comment]
I don't think, you need to buy it twice if you want to use it like that and want to brand your rainloop install.
But to circumvent the problem with an owncloud user logging in the "wrong way", a separate installation for non oC users would be the best way.
So you separate this two groups of users and it will  be more easy to maintain.

**Comment by RainLoop** [comment]
Since 1.9.0+ version local contacts are allowed in the ownCloud package.
