### ISSUE TITLE
Default identity not used when replying

### ISSUE THREAD

**Issue by JohanE67** [RainLoop/rainloop-webmail#561]
My e-mail address is different from my login name. I set up an alternate identity for my actual e-mail address and made that identity the default.
When I reply to a message that is sent directly to my e-mail address, there is no problem: the "from" in the reply is my default identity/e-mail address.
However, when I reply to a message that is sent to e.g. an e-mailgroup that I'm part of, the reply is set to my login-id (non-existing e-mail), instead of my default identity/e-mail address.

I'm using the rainloop owncloud plugin. rainloop v1.8.2.291 ; owncloud v8.0.2 on Ubuntu server 12.04.

**Comment by RainLoop** [comment]
Probably this messages contain your login-id (non-existing e-mail) and RainLoop gets it for reply.

**Comment by JohanE67** [comment]
That's probably true. It is the eventual "Deliver-to" name. But that is true for ALL messages delivered to me and if my primary identity is in the "To" line, there is no problem.
What's the point of setting a primary/default identity if Rainloop decides on its own to use something else instead? I would assume that the chosen identity would be used regardless of creating or answering to whatever message in that account.

**Comment by RainLoop** [comment]
Try to check the latest version.

**Comment by zsuiram** [comment]
Same issue here. Chosen *default identity* is not picked in **Settings>General**, but is marked as default in **Settings>Identities**.

On top this does not only work in replies but also in newly created mails. Recipients always see Login-Name and Login-Server.

Btw. this is broken since update to 1.9.1.330 (community version).

**Comment by RainLoop** [comment]
> Chosen default identity is not picked in Settings>General

It is not a default identity.

> Recipients always see Login-Name and Login-Server.

Interesting, and what do you see on compose screen?

**Comment by zsuiram** [comment]
Yep, it's picked in **Settings>Identies** where *default identity* is actually picked.

When composing a message it's picked correctly. Showing default name and email and signature.
Issue is actually when receiving the composed mail though. 

In **FROM field* user login and login server are shown.

**Comment by RainLoop** [comment]
Well, it looks like mail server issue. 
Some mail servers replace FROM header in the message (Gmail for example)

You can check result emails in the SENT folder.

**Comment by zsuiram** [comment]
Thought so, too. But even in SENT folder header message is changed. Tested with other clients and they resolved just fine.

For now, will reinstall RL and check if this issue goes away. Will let you know then.

**Comment by zsuiram** [comment]
OK, re-installed latest version and re-configured the application. Same thing appears.
Then double checked if some settings were changed on the server.. last change was 3 months ago.

Using following settings:
imap_port = 993
imap_secure = "SSL"
smtp_port = 587
smtp_secure = "TLS"
smtp_auth = On
allow_additional_accounts = Off
allow_additional_identities = On

Has SMTP libs changed since last release?

**Comment by zsuiram** [comment]
Ok, updated to latest version and it seems to work again.
Just FYI: Before that i turned on log and received some **533 5.7.1** errors.

Anyway, thanks for fixing!
