### ISSUE TITLE
1.8.3 (RC)

### ISSUE THREAD

**Issue by RainLoop** [RainLoop/rainloop-webmail#582]
version: 1.8.3.301

http://repository.rainloop.net/v2/webmail/1.8.3/rainloop-1.8.3.301-f1e8447e29f0cf7a331032ca7ae41779.zip

* Encforce 2-Step verification

* New tooltips style

![8](https://cloud.githubusercontent.com/assets/5530092/7098192/267de36c-dfe6-11e4-85b5-9566632c3a03.gif)

* Translatable admin panel

![image](https://cloud.githubusercontent.com/assets/5530092/7098142/b0ec81e4-dfe5-11e4-9a89-614f3fcdf43c.png)

* Simple audio player for mp3 attachments

![9](https://cloud.githubusercontent.com/assets/5530092/7098127/75365170-dfe5-11e4-880d-db6796ee023f.gif)

**Comment by jelle-e** [comment]
Wow, that's just fantastic! Thanks for your innovations :)

**Comment by megadr01d** [comment]
It would make more sense for the pause button to be in the same place where the play button is. If the goal is to be able to play a mp3 in the background while being able to switch to another message, I think this is bloating Rainloop to much.

Also prefer the old style tooltips. Not for the style itself (I like the new white theme) but because they just faded in, without shifting the actual tooltip vertically (which this new animation does).

Anyway, I gladly welcome the new additions because Rainloop is a project done with passion and that's what impresses me the most. Great job.

**Comment by RainLoop** [comment]
@megadr01d 

> If the goal is to be able to play a mp3 in the background
> while being able to switch to another message, I think this is bloating Rainloop to much.

I don't thinks so. By default all controls are hidden and do not bloat UI.
Most users will never see it. This is the first step to support voice messages. 

> Also prefer the old style tooltips. Not for the style itself (I like the new white theme) 
> but because they just faded in, without shifting the actual tooltip vertically
> (which this new animation does).

Agree

![10](https://cloud.githubusercontent.com/assets/5530092/7102172/09c3eae6-e081-11e4-8e49-b2dd9bbba8fa.gif)

> Anyway, I gladly welcome the new additions because Rainloop is a project done
>  with passion and that's what impresses me the most. Great job.

Thanks!

**Comment by RainLoop** [comment]
version: 1.8.3.301

http://repository.rainloop.net/v2/webmail/1.8.3/rainloop-1.8.3.301-f1e8447e29f0cf7a331032ca7ae41779.zip

**Comment by megadr01d** [comment]
:+1:

**Comment by skibbipl** [comment]
I can't expand threaded messages on the list. It is by design? How can I mark an email as unread in the middle of conversation?

**Comment by RainLoop** [comment]
> I can't expand threaded messages on the list. It is by design? 

Yes, now you should use a new dropdown for that.

![image](https://cloud.githubusercontent.com/assets/5530092/7143718/a5d9f7c6-e2e9-11e4-9f38-00e28ce330e4.png)


> How can I mark an email as unread in the middle of conversation?

Is it really necessary?

**Comment by skibbipl** [comment]
I really miss this feature as I used it in my workflow to mark tasks for executing later. Also there is no way to star a message in the middle of conversation. I can't force you to change the behaviour, but I would really appreciate if you consider adding it in future version.

**Comment by RainLoop** [comment]
ok

**Comment by RainLoop** [comment]
@skibbipl 
Maybe flagging?

![image](https://cloud.githubusercontent.com/assets/5530092/7147324/d0e69370-e302-11e4-9d8d-ffbc687bd5ec.png)

**Comment by megadr01d** [comment]
> How can I mark an email as unread in the middle of conversation?
> ...
> Is it really necessary?

After using the new thread system for a while and being puzzled on why I couldn't [delete a thread message](https://github.com/RainLoop/rainloop-webmail/issues/523#issuecomment-92912977), I have to agree I prefer the old system.

I mean, in a design perspective, the new system drop-down is very cool and you can quickly browse through messages but... it seems that functionality had to be thrown away. It's like messages in a thread are treated differently from regular messages. They became almost irrelevant, untouchable. It's not even possible to <kbd>⌘ + Click</kbd> messages in a thread and you easily lose track on which message you are, in a conversation, and keep pressing <kbd>Cmd + →/←</kbd>, because there's no visual representation of the thread hierarchy at all times, anymore (I have to press <kbd>T</kbd> every time, for that, but the selection always starts at the top and I must keep pressing <kbd>↓</kbd> on long threads just to get to the last selected thread).

As @skibbipl points out, the ability to expand a thread right in the message list, check all received dates side by side, browse like any other message, mark read or unread (why not, they're still regular messages), star, delete, be selected with check marks, etc., didn't sacrifice any usability and still looked cool (like Apple's Mail.app).

I'm sorry I speak my mind so often but as much as I like aesthetics, I wouldn't sacrifice usability for it.
I don't know, maybe some middle-ground can be found.

**Comment by RainLoop** [comment]
@megadr01d 

The main idea that this is not a message list, it is one big message (conversation).

> messages in a thread and you easily lose track on which message you are,

![image](https://cloud.githubusercontent.com/assets/5530092/7148527/5f7295ae-e30c-11e4-85c1-9f700e680587.png)

> I have to press T every time, for that, but the selection always starts at the top
> and I must keep pressing ↓ on long threads just to get to the last selected thread.

It will be fixed. This will work as you expect.

**Comment by ervee** [comment]
I'm sorry @RainLoop. I don't want to want to let you down because you do a lot of awesome stuff, but I have to agree with @megadr01d... I tried it, I didn't like it much and now I disabled threading completely. For the most past I miss the ability to see, select messages with checks and then do stuff with them in the message list.

I understand it has been a lot of work to get to this design and probably too much has changed to have an option to at least let the user choose which thread method he/she wants?

**Comment by megadr01d** [comment]
> and now I disabled threading completely.

I'm afraid I had to disable it too. I can't use any hotkeys (unread, archive, move, flag) on specific messages.

> The main idea that this is not a message list, it is one big message (conversation).

But in the end, it's not really one big message, is it? They're just several different messages fetched from the mail server. We may view them like one big message but manage them like individual messages.

**Comment by megadr01d** [comment]
Still about the tooltips, how about an option in `application.ini` to disable them? Don't mean to be *persona non grata* but after a while, they just get in the way. There are not too many buttons and they're easy to memorize anyway.

**Comment by RainLoop** [comment]
![gne](https://cloud.githubusercontent.com/assets/5530092/7262399/dec9dad6-e881-11e4-9da1-98f600fe0170.jpg)

Old thread list is back! Hooray!
And now it works more better!

![11](https://cloud.githubusercontent.com/assets/5530092/7262374/b969c904-e881-11e4-8908-a020e3346d95.gif)

http://repository.rainloop.net/v2/webmail/1.8.3/rainloop-1.8.3.305-c5f7757e72a0b67e124de5ced6330baa.zip

**Comment by ervee** [comment]
Hooray! :)
I'm testing the release. It looks like sometimes RainLoop now opens a random message after going back to the message list. But I'm not quite sure.

I do have some feedback though :) Off course... ;) I personally don't think the location of the message thread counter is at an intuitive position at the moment.

Ralf

**Comment by RainLoop** [comment]
> I personally don't think the location of the message thread counter
> is at an intuitive position at the moment.

Waiting for your suggestions :).

**Comment by skibbipl** [comment]
The solution with expandable threads is great! Can't wait to test it in stable version.
Regarding thread counter - is it possible to expand thread by double clicking on the threaded message?

**Comment by RainLoop** [comment]
hm, it's a good idea.

**Comment by RainLoop** [comment]
#606

**Comment by megadr01d** [comment]
Thank you, professor Farnsworth.
