### ISSUE TITLE
Match sender address to "To: " header

### ISSUE THREAD

**Issue by thonixx** [RainLoop/rainloop-webmail#693]
You can configure multiple identities with multiple names and mail addresses. Imagine you have catchall configured and you receive mails for everything@xy.tld. Then you have mail1@xy.tld and mail2@xy.tld configured as identities.
Now you click on "reply" on the mail which was sent to mail2@xy.tld and the identity with mail2@xy.tld should be chosen. But in real the first and default identity gets selected and you reply with mail1@xy.tld instead of mail2@xy.tld.

**Comment by RainLoop** [comment]
Hi, it should work correctly. Do you use the latest version of RainLoop Webmail?

**Comment by megadr01d** [comment]
Just to confirm it works correctly in the latest version.

**Comment by thonixx** [comment]
Yes, installed the latest available version some hours ago. And it does not work in my setup. Can I provide you any kind of logs or something like that for debugging?

**Comment by punkkeks** [comment]
Same problem here as well. Also using the latest version and it does not work properly :/

**Comment by CyberJack** [comment]
Same problem here, using version 1.9.1.335.

**Comment by greg-1-anderson** [comment]
Not working for me on 1.9.2.343.

**Comment by greg-1-anderson** [comment]
The function that controls this is [findIdentityByMessage](https://github.com/RainLoop/rainloop-webmail/blob/1.6.11/dev/View/Popup/Compose.js#L459), which appears correct by casual inspection. (n.b. the code in the master branch is different, but pretty close to the old implementation I linked to for stability's sake, since line numbers in the master branch are going to change.) 

Seems that one or more of the variables used in this function must be uninitialized for those of us who find this feature not to be working.

I wanted to try making some changes here, to see what would happen, but I couldn't find any instruction on how to build, or how to deploy from the GitHub sources (the installed app appears to be minified, etc.)
Anyone able to help out here?

**Comment by greg-1-anderson** [comment]
Moved build instructions to #795.
