### ISSUE TITLE
Wrong mail counter

### ISSUE THREAD

**Issue by skibbipl** [RainLoop/rainloop-webmail#698]
Hi,
It seems latest RL displays invalid messages count:
![mail](https://cloud.githubusercontent.com/assets/4746858/7916724/f60bbc7c-0885-11e5-9a6f-cdc05758b179.png)
I think it might be related to writing emails in thunderbird while RL opened in browser. Any ideas how to debug this?

Regards

**Comment by RainLoop** [comment]
Interesting, RainLoop does not display messages marked deleted.
Maybe that's the problem.

**Comment by megadr01d** [comment]
This used to happen to me 4 or so versions ago while composing in Apple's Mail and having Rainloop open. I would get ~15 drafts in Rainloop. Now I just tested composing 2 messages in Mail, and it only correctly saved 2 drafts in both Mail and Rainloop which were deleted after sending the messages so it's working fine on my end (I don't think it has anything to do with the messages marked deleted feature).

You may have to refresh Rainloop for the correct count to be updated.

**Comment by skibbipl** [comment]
I tried to refresh several times, but without success. Perhaps there is some kind of lock that thunderbird creates in Drafts folder. Anyway after some time my drafts counter is 0 again.

**Comment by megadr01d** [comment]
In Mail.app there's also a "Sync all accounts" which usually fixes things like that (wrong counts in Mail.app itself or temporary email fetching errors).

**Comment by megadr01d** [comment]
FYI, I had this problem today and synching accounts in my local email client didn't fix it. I had to clear all browser cache for the Drafts count to update correctly from 11 to 2.

**Comment by megadr01d** [comment]
Using the latest 1.10.4.183, I confirmed this is still an issue.

Clearing the browser cache no longer fixes it but, maybe because of [this](https://github.com/RainLoop/rainloop-webmail/issues/1030) workaround by the Rainloop team, I was able to clear the incorrect count on the *Drafts* folder by either using the **Rebuild** command in Apple Mail (not sure if other local mail clients support this) or selecting the *Drafts* folder in Rainloop's webmail, clicking on the **More** toolbar icon and finally selecting **Clear Folder**.
