### ISSUE TITLE
License: switch to a software license

### ISSUE THREAD

**Issue by alexei** [RainLoop/rainloop-webmail#8]
CC licenses are not commonly used for software. See also http://wiki.creativecommons.org/FAQ#Can_I_use_a_Creative_Commons_license_for_software.3F

**Comment by pierstaylor** [comment]
I have to say, and I am in the unfortunate position of having to figure out what licenses mean when using various open source projects at work, that I don't think the license means what the RainLoop people think it means. The very fact that the CC people do not recommend its use for software should give you a clue here.

RainLoop - not unreasonably, would like to protect their IP (although they seem to have a number of contributors, and so there may be questions of shared IP here).

If you want to protect your IP (having established what you actually own) and taking account of the IP that others certainly own (for example covered by the licenses governing use of third party code libraries being included in the product) you need to be absolutely sure of the legal stand point - otherwise your licensing might be quite pointless and NOT protecting you at all.

There are two ways to do this - one is to use a well understood license that you apply in a way that it is commonly used, following the recommendations of the license creators. The other is to use a lawyer to help you draft or choose a license.

In either case you, or your advisers really do have to understand what you are doing, and what the legal implications are.

If the CC people say that their license should not be used for software, it means that, form a legal standpoint, they *already know* there are legal issues with it. You should therefore *not use it that way*, because you are at risk - it is not offering you, your code and IP protection.

I am not going to presume to tell you what license you *should* be using, because that is going to depend on what you are trying to achieve. Although I might have an opinion on that, I think that the subject is sufficiently complex and sufficiently important that you, RainLoop, really must look into this yourselves.

I like your product, and I am using it within the terms that I understand you intend by your use of the CC license.

But please - give this some serious thought and, if necessary, seek some legal advice. You should not be using CC - because they say you should not be using it!

Best wishes,

P.

**Comment by RainLoop** [comment]
RainLoop Webmail (Community edition) licensed under AGPLv3.
