### ISSUE TITLE
Reply on Reply

### ISSUE THREAD

**Issue by drpain** [RainLoop/rainloop-webmail#828]
Not sure if this has been fixed, but I am experiencing an issue where. If I had replied to someone, and they have not replied back. And I then try and send a follow up email, then I end up replying to myself and not the other party. 

I do have message stacking enabled, if this information helps.

**Comment by megadr01d** [comment]
I can't reproduce this. I reply to someone and then reply again and the **To** field is always set to the original recipient, even in a threaded message conversation.

**Comment by drpain** [comment]
It definitely happens to me. It's cool, I will update and check if it still happens. I was wondering if it's a known issue.

**Comment by arturbonnett** [comment]
It happens to me too. My instaled version is up to date (RainLoop/1.9.2.353).
It's understandable this non-priority bug. Rainloop just follows the correct logic.
To solve this incovenience, Rainloop should check if the current user is the "from" field, so if positive, uses "to" to reply.

A header example of reply send from me that when I click to reply again 'reply to me' instead of who I want:
```
Mime-Version: 1.0
Date: Thu, 03 Sep 2015 13:33:11 +0000
Content-Type: multipart/alternative;
 boundary="--=_RainLoop_881_235550312.1441287191"
Message-ID: <830b374fc03c96cb1ff3eaa3a4fb2e0d@mine-domain.com>
X-Mailer: RainLoop/1.9.2.353
From: "=?utf-8?B?QXJ0dXIgQm9ubmV0dCAtIEFnw6puY2lhIFN1cnh?=" <me@mine-domain.com>
Subject: Re: xxxxxxxx xxxxxxxxxx
To: other-person@other-domain.net
In-Reply-To: <b87a8e4627df32591462613ffefbad39@other-domain.net>
References: <b87a8e4627df32591462613ffefbad39@other-domain.net>
 <da77b0ec9548f86be8268ec0af4c9cdf@mine-domain.com>
```

**Comment by ervee** [comment]
@megadr01d , when you reply again, do you press reply on the last message YOU sent, from you sent items?

Because when I do, I defensively reply to myself. This is because I reply on an email I sent to someone. So the sender is me and the reply will go to me.

The logic is correct. And even Ms Outlook does it like that.

I always work around this by using reply to all. In RainLoop you then have to remove your own email address (and possibly others you don't need). Outlook automatically removes your own email address from the To field. This could be improved in RainLoop.

Ralf.

**Comment by arturbonnett** [comment]
Hi @ervee, I just verify that Outlook (online) and Gmail, when answering a reply sent by me in the Sent folder, both understand that I want to send to the other person correctly, not to me.

**Comment by ervee** [comment]
Ah well Outlook 2010 sure isn't that smart :) I also have a webmail system (OpenWebmail) which doesn't have an option to reply to email in your sent folder.

I guess it makes sense that if you reply to a sent item, you actually don't want to send it to yourself. but on the other hand, when it does it does what it's supposed to do, reply to the sender, you :)

Perhaps @RainLoop can comment on this. Go all computer logic and reply to self, or try to be smart and reply to the recipient when pressing reply on a sent item... ?

**Comment by megadr01d** [comment]
Actually, I think the way Gmail and Outlook does it (I don't use either one) it's meant to be idiot-proof (not directed at you, guys, of course, but at a vast majority with less computer knowledge), so the *smart* way is how Rainloop does it. Perhaps the Rainloop team could consider doing it the dumb way...

Multiple replies should always be done on the original email so, if it's not in your inbox anymore, it's probably in the Trash, not the Sent folder.

**Comment by drpain** [comment]
The idea is that sometimes you answer someone, but it doesn't implicitly require a reply from them. Then you want to follow up, and in a threaded mail, when I reply on the mail. 

It should send it to the other part. It's not super complex logic I am sure. You know the user's email address, why not check that they are sending to themselves, or correctly match the other participating party. 

Or as alternative, always thread the emails with the last reply from the other party on top.
