### ISSUE TITLE
Update Rainloop for ownCloud 8.2

### ISSUE THREAD

**Issue by aspdye** [RainLoop/rainloop-webmail#870]
see Title :D

**Comment by HLFH** [comment]
@RainLoop I'm just saying that [RainLoop works for me on ownCloud 8.2](https://apps.owncloud.com/content/show.php/RainLoop+Webmail?content=165254). So, finally, we just need a small update. Thanks!

**Comment by HLFH** [comment]
@RainLoop Hi. Could you update the [Rainloop package for ownCloud 8.2.2](https://apps.owncloud.com/content/show.php/RainLoop+Webmail?content=165254)? Now, on Transifex, the Rainloop admin panel is translated in French. I would love to use it in French so with ownCloud. And it now seems [you are using .yml files instead of .ini files for localization](https://github.com/RainLoop/rainloop-webmail/tree/master/rainloop/v/0.0.0/app/localization). So, it would be great to get the last RainLoop package for ownCloud 8.2.2. What do you think?

**Comment by RainLoop** [comment]
Done

**Comment by HLFH** [comment]
Yes, I tried when you released it. And it works like a charm. Thank you!
