### ISSUE TITLE
PDO password stored in plain text

### ISSUE THREAD

**Issue by Fointard** [RainLoop/rainloop-webmail#979]
Hi everyone,
I use rainloop on my server and it rocks, thx 2 u 4 developing such a great software !
Nevertheless, I couldn't help but notice the pdo password used to connect to the contact-storing DB is stored in plain text in application.ini, ain't this kind of practice ugly as f*ck ?
Fointard

**Comment by pietroalbini** [comment]
How would you store that? I'm curious.

**Comment by Fointard** [comment]
I'm ain't sure i'm not saying sth stupid as i'm not an expert but mysql seems to provide several authentication methods including a "secure password" which involves SHA1 only.

https://dev.mysql.com/doc/internals/en/secure-password-authentication.html

It's not perfect as the SHA1 has to be stored anyway but at least the password itself can't be intercepted w/ wireshark or whatever capturing software one might use.

Moreover users that have one password for several services (yeah, some people still do...) might like that it's not written 'as-is' in a file.

What do you think ?

**Comment by pietroalbini** [comment]
You're right, users' passwords must be stored hashed (with something stronger than sha1, for example bcrypt/scrypt/argon2), because if someone steals the database's content (or the website owner turns evil), it's *really* difficult to obtain the original password.

The thing is, we're not talking about users' passwors here, but about the password used by the application to connect to the database. And that must not be hashed, because RainLoop needs it in plaintext to connect to the database.

**Comment by Fointard** [comment]
I totally agree w/ the first part of your answer but I just don't wan't anyone else to have access to my contacts DB by sniffing my network (or have access to other equipments in case I chose identical passwords for several machines/services/etc...) and I was wondering if storing a hash could suffice as MySQL seems to provide an auth method that relies on it ?

**Comment by pietroalbini** [comment]
But the database password is never sent on the network. It's used by RainLoop internally to connect to the database, fetch the contacts and return them to the client, but the connection is made by the server, not by the client. The only way to read the password in that file is to have access to the machine.

By the way, it doesn't make sense to hash the database password, because if the database accepts the hashed password for authentication, I could just use the hash I got from sniffing the network to log into it (thus the hashed password becomes the real password).

**Comment by Fointard** [comment]
Rainloop (aka whatever webserver u use) & MySQL might run on different hosts, in that case the password has to transit over the network.
& the database does not accept the hashed password 'as-is', instead it sends a "random sequence" that has to be combined (XORed or sth by some algorithm) with the hash prior to be sent back to the DB. This way, sniffers can't intercept passwords.
But in the end hashing that password is only useful for careless admins who use the same password in different places, mmmh.
Much trouble for a small improvment, it's just that i'm not used to see plain-text stored passwords after all... Shall I close this ?

**Comment by pietroalbini** [comment]
> Rainloop (aka whatever webserver u use) & MySQL might run on different hosts, in that case the password has to transit over the network.

In this case it's your job to secure this network, for example with a VPN.

The thing is, MySQL wants you to submit a plaintext password in order to log into it (even if it's encrypted in the network transport), and there is no way to avoid storing that somewhere, if you don't want to type that every connection ;-)

**Comment by Fointard** [comment]
You're right, thx 4 sharing !
